---

image: clojure:openjdk-11-tools-deps

stages:
  - build
  - publish

services:
  - name: docker:dind
    command: ["--insecure-registry=docker.harrigan.online:8083", "--registry-mirror=https://docker.harrigan.online"]

before_script:
  - "git describe --match='rel/*' --exact-match && export PROJECT_VERSION=$(git describe --match='rel/*' | sed 's:^rel/::') || true"

cache:
  key: $CI_PROJECT_NAME

build:
  stage: build
  script:
    - clojure -A:build-prod
  artifacts:
    paths:
      - target
    expire_in: 1 day
  tags:
    - build

publish:docker:clojure:
  stage: publish
  dependencies:
    - build
  image: docker:latest
  variables:
    IMAGE: $DOCKER_REGISTRY:8083/$CI_PROJECT_PATH
  script:
    - export TAG=$(echo -en ${CI_COMMIT_REF_NAME#rel/} | tr -c '[:alnum:]_.-' '-')
    - export IMAGE_NAME="$IMAGE:$TAG"
    - docker build --pull -f scripts/docker/Dockerfile -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - /^rel\//
  tags:
    - publish
